experiment_name: eye3_mixed_plus_eye_dataset_plus_badcase_swin_tiny_128_drop_path_01
output_dir: outputs
seed: 42

data:
  image_size: 128
  batch_size: 256
  eval_batch_size: 256
  num_workers: 8
  pin_memory: true
  train_augment:
    rotation_degrees: 15
    rotation_p: 0.50
    gaussian_blur_p: 0
    gaussian_blur_kernel_size: 7
    gaussian_blur_sigma: [0.1, 2.0]
    jpeg_compression_p: 0
    jpeg_quality: [25, 85]
    random_erasing_p: 0
    random_erasing_scale: [0.02, 0.12]
    random_erasing_ratio: [0.3, 3.3]
    random_erasing_value: 0
  train_augment_by_class:
    closed:
      blue_purple_p: 0.20
      blue_purple_strength: [0.08, 0.20]
      grayscale_p: 0.20
      low_contrast_p: 0.30
      brightness: [0.70, 1.15]
      contrast: [0.45, 1.0]
      saturation: [0.0, 1.0]
      random_erasing_p: 0
      random_erasing_scale: [0.02, 0.12]
      random_erasing_ratio: [0.3, 3.3]
      random_erasing_value: 0
    open:
      blue_purple_p: 0.20
      blue_purple_strength: [0.08, 0.20]
      grayscale_p: 0.20
      low_contrast_p: 0.30
      brightness: [0.70, 1.15]
      contrast: [0.45, 1.0]
      saturation: [0.0, 1.0]
      random_erasing_p: 0
      random_erasing_scale: [0.02, 0.12]
      random_erasing_ratio: [0.3, 3.3]
      random_erasing_value: 0
  datasets:
    - name: blink_dataset
      root: /home/featurize/data/blink_dataset
      class_map:
        closed: 0
        open: 1
        irrelevant: 2
    # badcase is split into two independent ImageFolder-style datasets.
    - name: badcase_case1
      root: /home/featurize/data/badcase/case1_dataset
      class_map:
        closed: 0
        open: 1
    - name: badcase_case2
      root: /home/featurize/data/badcase/case2_dataset
      class_map:
        closed: 0
        open: 1

model:
  name: swin_tiny_patch4_window7_224.ms_in1k
  pretrained: true
  kwargs:
    img_size: 128
    drop_path_rate: 0.01

train:
  device: cuda
  epochs: 40
  lr: 0.00005
  weight_decay: 0.05
  warmup_epochs: 4
  amp: true
  class_weight: false
  report_dataset_metrics: true
  save_best_dataset_metrics: true
  selection_metric: mean_closed_open
  early_stopping_patience: 8
  early_stopping_min_delta: 0.0005
