experiment_name: mrl_resnet50_finetune
output_dir: outputs
seed: 42

data:
  image_size: 224
  batch_size: 128
  eval_batch_size: 256
  num_workers: 8
  pin_memory: true
  datasets:
    - root: /home/featurize/data/data
      class_map:
        sleepy: 0
        awake: 1

model:
  name: resnet50
  pretrained: true

train:
  device: cuda
  epochs: 30
  lr: 0.00005
  weight_decay: 0.05
  warmup_epochs: 2
  amp: true
  class_weight: false
